const couchModel = require('../models/couchConnectionModel');
const couchConn  = new couchModel('localhost', '5984');
const couchAdapter = require('../lib/couchAdapter');
const couchdb = new couchAdapter(couchConn);

const skillCollection = couchdb.createDatabase('gear');
skillCollection.bulk({docs: [{
    _id: 'combat_axe',
    name: 'Combat Axe',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 4,
    reach: 2,
    damage: 'STR + 5',
    damageType: 'P',
    armorPiercing: -4,
    avail: '12R',
    cost: 4000
}, {
    _id: 'combat_knife',
    name: 'Combat Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -3,
    avail: '4',
    cost: 300
}, {
    _id: 'forearm_snap_blades',
    name: 'Forearm Snap-Blades',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: true,
    accuracy: 4,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -2,
    avail: '7R',
    cost: 200
}, {
    _id: 'katana',
    name: 'Katana',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 7,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -3,
    avail: '9R',
    cost: 1000
}, {
    _id: 'knife',
    name: 'Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: -1,
    avail: null,
    cost: 10
}, {
    _id: 'pole_arm',
    name: 'Pole Arm',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 5,
    reach: 3,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -2,
    avail: '6R',
    cost: 1000
}, {
    _id: 'survival_knife',
    name: 'Survival Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -1,
    avail: null,
    cost: 100
}, {
    _id: 'sword',
    name: 'Sword',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 6,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -2,
    avail: '5R',
    cost: 500
}, {
    _id: 'club',
    name: 'Club',
    type: 'melee_weapon',
    group: 'Clubs',
    wireless: false,
    accuracy: 4,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: 0,
    avail: null,
    cost: 30
}, {
    _id: 'extendable_baton',
    name: 'Extendable Baton',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 5,
    reach: 1,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '4',
    cost: 100
}, {
    _id: 'sap',
    name: 'Sap',
    type: 'melee_weapon',
    group: 'Club',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '2',
    cost: 30
}, {
    _id: 'staff',
    name: 'Staff',
    type: 'melee_weapon',
    group: 'Club',
    wireless: false,
    accuracy: 6,
    reach: 2,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: 0,
    avail: '3',
    cost: 100
}, {
    _id: 'stun_baton',
    name: 'Stun Baton',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 4,
    reach: 1,
    damage: '9',
    damageType: 'S(e)',
    armorPiercing: 0,
    avail: '4',
    cost: 100
}, {
    _id: 'telescoping_staff',
    name: 'Telescoping Staff',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 4,
    reach: 2,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '4',
    cost: 350
}, {
    _id: 'knucks',
    name: 'Knucks',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: false,
    accuracy: -1,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: 0,
    avail: '2R',
    cost: 100
}, {
    _id: 'monofilament_whip',
    name: 'Monofilament Whip',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: true,
    accuracy: 5(7),
    reach: 2,
    damage: '12',
    damageType: 'P',
    armorPiercing: -8,
    avail: '12F',
    cost: 10000
}, {
    _id: 'shock_gloves',
    name: 'Shock Gloves',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: true,
    accuracy: -1,
    reach: 0,
    damage: '8',
    damageType: 'S(e)',
    armorPiercing: -5,
    avail: '6R',
    cost: 550
}, {
    _id: 'bows',
    name: 'Bows',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: 'Rating + 2',
    damageType: 'P',
    armorPiercing: -1/4,
    avail: '1',
    cost: 100
}, {
    _id: 'light_crossbow',
    name: 'Light Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '5',
    damageType: 'P',
    armorPiercing: -1,
    avail: '2',
    cost: 300
}, {
    _id: 'medium_crossbow',
    name: 'Medium Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: -2,
    avail: '4R',
    cost: 500
}, {
    _id: 'heavy_crossbow',
    name: 'Heavy Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -2,
    avail: '8R',
    cost: 1000
}, {
    _id: 'bolt',
    name: 'Bolt',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 0,
    reach: 0,
    damage: null,
    damageType: null,
    armorPiercing: 0,
    avail: '2',
    cost: 5
}, {
    _id: 'injection_bolt',
    name: 'Injection Bolt',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 0,
    reach: 0,
    damage: null,
    damageType: null,
    armorPiercing: 0,
    avail: '8R',
    cost: 50
}, {
    _id: 'throwing_knife_shuriken',
    name: 'Throwing Knife/Shuriken',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: true,
    accuracy: 0,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: -1,
    avail: '4R',
    cost: 25
}, {
    _id: 'defiance_ex_shocker',
    name: 'Defiance EX Shocker',
    type: 'firearms',
    group: 'Tasers',
    wireless: true,
    accuracy: 4,
    reach: 0,
    damage: '9',
    damageType: 'S(e)',
    armorPiercing: -5,
    mode: 'SS',
    recoil: null,
    ammo: '4(m)',
    avail: null,
    cost: 250
}, {
    _id: 'yamaha_pulsar',
    name: 'Yamaha Pulsar',
    type: 'firearms',
    group: 'Tasers',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: '7',
    damageType: 'S(e)',
    armorPiercing: -5,
    mode: 'SA',
    recoil: null,
    ammo: '4(m)',
    avail: null,
    cost: 180
}, {
    _id: 'fichetti_tiffani_needler',
    name: 'Fichetti Tiffani Needler',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: '8',
    damageType: 'P(f)',
    armorPiercing: +5,
    mode: 'SA',
    recoil: null,
    ammo: '4(c)',
    avail: '5R',
    cost: 1000
}, {
    _id: 'streetline_special',
    name: 'Streetline Special',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '6(c)',
    avail: '4R',
    cost: 120
}, {
    _id: 'walther_palm_pistol',
    name: 'Walther Palm Pistol',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SS/BF',
    recoil: null,
    ammo: '2(b)',
    avail: '4R',
    cost: 180
}, {
    _id: 'ares_light_fire_75',
    name: 'Ares Light Fire 75',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6(8),
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '16(c)',
    avail: '6F',
    cost: 1250
}, {
    _id: 'ares_light_fire_70',
    name: 'Ares Light Fire 70',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '16(c)',
    avail: '3R',
    cost: 200
}, {
    _id: 'beretta_201T',
    name: 'Beretta 201T',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF',
    recoil: 1,
    ammo: '21(c)',
    avail: '7R',
    cost: 210
}, {
    _id: 'colt_america_L36',
    name: 'Colt America L36',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '11(c)',
    avail: '4R',
    cost: 320
}, {
    _id: 'fichetti_security_600',
    name: 'Fichetti Security 600',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6(7),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 1,
    ammo: '30(c)',
    avail: '6R',
    cost: 350
}, {
    _id: 'taurus_omni_6',
    name: 'Taurus Omni-6',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 5(6),
    reach: 0,
    damage: '6/7',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA/SS',
    recoil: null,
    ammo: '6(cy)',
    avail: '3R',
    cost: 300
}, {
    _id: 'ares_predator_v',
    name: 'Ares Predator V',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '8',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA',
    recoil: null,
    ammo: '15(c)',
    avail: '5R',
    cost: 725
}, {
    _id: 'ares_viper_slivergun',
    name: 'Ares Viper Slivergun',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '9',
    damageType: 'P(f)',
    armorPiercing: 4,
    mode: 'SA/BF',
    recoil: null,
    ammo: '30(c)',
    avail: '8F',
    cost: 380
}, {
    _id: 'browning_ultra_power',
    name: 'Browning Ultra-Power',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 5(6),
    reach: 0,
    damage: '8',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA',
    recoil: null,
    ammo: '10(c)',
    avail: '4R',
    cost: 640
}, {
    _id: 'colt_government_2066',
    name: 'Colt Government 20166',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA',
    recoil: null,
    ammo: '14(c)',
    avail: '7R',
    cost: 425
}, {
    _id: 'remington roomsweeper',
    name: 'Remington Roomsweeper',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA',
    recoil: null,
    ammo: '8(m)',
    avail: '6R',
    cost: 250
}, {
    _id: 'ruger_super_warhawk',
    name: 'Ruger Super Warhawk',
    type: 'firearms',
    group: 'Heavy Pistols',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '9',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'SS',
    recoil: null,
    ammo: '6(cy)',
    avail: '4R',
    cost: 400
}, {
    _id: 'ares_crusader_ii',
    name: 'Ares Crusader II',
    type: 'firearms',
    group: 'Machine Pistols',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF',
    recoil: 2,
    ammo: '40(c)',
    avail: '9R',
    cost: 830
}, {
    _id: 'ceska_black_scorpion',
    name: 'Ceska Black Scorpion',
    type: 'firearms',
    group: 'Machine Pistols',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF',
    recoil: 1,
    ammo: '35(c)',
    avail: '6R',
    cost: 270
}, {
    _id: 'steyr_tmp',
    name: 'Steyr TMP',
    type: 'firearms',
    group: 'Machine Pistols',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF/FA',
    recoil: null,
    ammo: '30(c)',
    avail: '8R',
    cost: 350
}, {
    _id: 'colt_cobra_tz_120',
    name: 'Colt Cobra TZ-120',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 4(5),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF/FA',
    recoil: 2(3),
    ammo: '32(c)',
    avail: '5R',
    cost: 660
}, {
    _id: 'fn_p93_praetor',
    name: 'FN P93 Praetor',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '8',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF/FA',
    recoil: 1(2),
    ammo: '50(c)',
    avail: '11F',
    cost: 900
}, {
    _id: 'hk_227',
    name: 'HK-227',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF/FA',
    recoil: (1),
    ammo: '28(c)',
    avail: '8R',
    cost: 730
}, {
    _id: 'ingram_smartgun_x',
    name: 'Ingram Smartgun X',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 4(6),
    reach: 0,
    damage: '8',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'BF/FA',
    recoil: 2,
    ammo: '32(c)',
    avail: '6R',
    cost: 800
}, {
    _id: 'sck_model_100',
    name: 'SCK Model 100',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '8',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF',
    recoil: (1),
    ammo: '30(c)',
    avail: '6R',
    cost: 875
}, {
    _id: 'uzi_iv',
    name: 'Uzi IV',
    type: 'firearms',
    group: 'Submachine Guns',
    wireless: false,
    accuracy: 4(5),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'BF',
    recoil: (1),
    ammo: '24(c)',
    avail: '4R',
    cost: 450
}, {
    _id: 'ak_97',
    name: 'AK-97',
    type: 'firearms',
    group: 'Assault Rifles',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'SA/BF/FA',
    recoil: 0,
    ammo: '38(c)',
    avail: '4R',
    cost: 950
}, {
    _id: 'ares_alpha',
    name: 'Ares Alpha',
    type: 'firearms',
    group: 'Assault Rifles',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '11',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'SA/BF/FA',
    recoil: 2,
    ammo: '42(c)',
    avail: '11F',
    cost: 2650
}, {
    _id: 'colt_m23',
    name: 'Colt M23',
    type: 'firearms',
    group: 'Assault Rifles',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '9',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'SA/BF/FA',
    recoil: 0,
    ammo: '40(c)',
    avail: '4R',
    cost: 550
}, {
    _id: 'fn_har',
    name: 'FN HAR',
    type: 'firearms',
    group: 'Assault Rifles',
    wireless: false,
    accuracy: 5(6),
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'SA/BF/FA',
    recoil: 2,
    ammo: '35(c)',
    avail: '8R',
    cost: 1500
}, {
    _id: 'yamaha_raiden',
    name: 'Yamaha Raiden',
    type: 'firearms',
    group: 'Assault Rifles',
    wireless: false,
    accuracy: 6(8),
    reach: 0,
    damage: '11',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'BF/FA',
    recoil: 1,
    ammo: '60(c)',
    avail: '14F',
    cost: 2600
}, {
    _id: 'ares_desert_strike',
    name: 'Ares Desert Strike',
    type: 'firearms',
    group: 'Sniper Rifles',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '13',
    damageType: 'P',
    armorPiercing: -4,
    mode: 'SA',
    recoil: (1),
    ammo: '14(c)',
    avail: '10F',
    cost: 17500
}, {
    _id: 'cavalier_arms_crockett_ebr',
    name: 'Cavalier Arms Crockett EBR',
    type: 'firearms',
    group: 'Sniper Rifles',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '12',
    damageType: 'P',
    armorPiercing: -3,
    mode: 'SA/BF',
    recoil: (1),
    ammo: '20(c)',
    avail: '12F',
    cost: 10300
}, {
    _id: 'ranger_arms_sm_5',
    name: 'Ranger Arms SM-5',
    type: 'firearms',
    group: 'Sniper Rifles',
    wireless: false,
    accuracy: 8,
    reach: 0,
    damage: '14',
    damageType: 'P',
    armorPiercing: -5,
    mode: 'SA',
    recoil: (1),
    ammo: '15(c)',
    avail: '16F',
    cost: 28000
}, {
    _id: 'remington_950',
    name: 'Remington 950',
    type: 'firearms',
    group: 'Sniper Rifles',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '12',
    damageType: 'P',
    armorPiercing: -4,
    mode: 'SS',
    recoil: 0,
    ammo: '5(m)',
    avail: '4R',
    cost: 2100
}, {
    _id: 'ruger_101',
    name: 'Ruger 101',
    type: 'firearms',
    group: 'Sniper Rifles',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '11',
    damageType: 'P',
    armorPiercing: -3,
    mode: 'SA',
    recoil: (1),
    ammo: '8(m)',
    avail: '4R',
    cost: 1300
}, {
    _id: 'defiance_t_250',
    name: 'Defiance T-250',
    type: 'firearms',
    group: 'shotguns',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SS/SA',
    recoil: 0,
    ammo: '5(m)',
    avail: '4R',
    cost: 450
}, {
    _id: 'enfield_as_7',
    name: 'Enfield AS-7',
    type: 'firearms',
    group: 'shotguns',
    wireless: false,
    accuracy: 4(5),
    reach: 0,
    damage: '13',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA/BF',
    recoil: 0,
    ammo: '10(c) or 24(d)',
    avail: '12F',
    cost: 1100
}, {
    _id: 'pjss_model_55',
    name: 'PJSS Model 55',
    type: 'firearms',
    group: 'shotguns',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '11',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SS',
    recoil: (1),
    ammo: '2(b)',
    avail: '9R',
    cost: 1000
}, {
    _id: 'ares_s_iii_super_squirt',
    name: 'Ares S-III Super Squirt',
    type: 'firearms',
    group: 'Special Weapons',
    wireless: false,
    accuracy: 3,
    reach: 0,
    damage: null,
    damageType: 'chemical',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 0,
    ammo: '20(c)',
    avail: '7R',
    cost: 950
}, {
    _id: 'fichetti_pain_inducer',
    name: 'Defiance T-250',
    type: 'firearms',
    group: 'Special Weapons',
    wireless: false,
    accuracy: 3,
    reach: 0,
    damage: null,
    damageType: 'special',
    armorPiercing: 0,
    mode: 'SS',
    recoil: 0,
    ammo: 'Special',
    avail: '11R',
    cost: 5000
}, {
    _id: 'parashield_dart_pistol',
    name: 'Parashield Dart Pistol',
    type: 'firearms',
    group: 'Special Weapons',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: null,
    damageType: 'Drug/Toxin',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 0,
    ammo: '5(c)',
    avail: '4R',
    cost: 600
}, {
    _id: 'parashield_dart_rifle',
    name: 'Parashield Dart Rifle',
    type: 'firearms',
    group: 'Special Weapons',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: null,
    damageType: 'Drog/Toxin',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 0,
    ammo: '6(m)',
    avail: '6R',
    cost: 1200
}, {
    _id: 'ingram_valiant',
    name: 'Ingram Valiant',
    type: 'firearms',
    group: 'Machine Guns',
    wireless: false,
    accuracy: 5(6),
    reach: 0,
    damage: '9',
    damageType: 'P',
    armorPiercing: -2,
    mode: 'BF/FA',
    recoil: 2(3),
    ammo: '50(c) or 100(belt)',
    avail: '12F',
    cost: 5800
}, {
    _id: 'stoner_ares_m202',
    name: 'Stoner Ares M202',
    type: 'firearms',
    group: 'Machine Guns',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -3,
    mode: 'FA',
    recoil: 0,
    ammo: '50(c) or 100(belt)',
    avail: '12F',
    cost: 7000
}, {
    _id: 'rpk_hmg',
    name: 'RPK HMG',
    type: 'firearms',
    group: 'Machine Guns',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '12',
    damageType: 'P',
    armorPiercing: -4,
    mode: 'FA',
    recoil: (6),
    ammo: '50(c) or 100(belt)',
    avail: '16F',
    cost: 16300
}, {
    _id: 'ares_antioch_2',
    name: 'Ares Antioch-2',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 4(6),
    reach: 0,
    damage: null,
    damageType: 'Grenade',
    armorPiercing: 0,
    mode: 'SS',
    recoil: 0,
    ammo: '8(m)',
    avail: '8F',
    cost: 3200
}, {
    _id: 'armtech_mgl_12',
    name: 'ArmTech MGL-12',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: null,
    damageType: 'Grenade',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 0,
    ammo: '12(c)',
    avail: '8F',
    cost: 3200
}, {
    _id: 'aztechnology_striker',
    name: 'Aztechnology Striker',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: null,
    damageType: 'Missle',
    armorPiercing: 0,
    mode: 'SS',
    recoil: 0,
    ammo: '1(ml)',
    avail: '10F',
    cost: 1200
}, {
    _id: 'krime_cannon',
    name: 'Krime Cannon',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '16',
    damageType: 'P',
    armorPiercing: -6,
    mode: 'SA',
    recoil: (1),
    ammo: '6(m)',
    avail: '20F',
    cost: 21000
}, {
    _id: 'onotari_interceptor',
    name: 'Onotari Interceptor',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 4(6),
    reach: 0,
    damage: null,
    damageType: 'Missle',
    armorPiercing: 0,
    mode: 'SS',
    recoil: 0,
    ammo: '2(ml)',
    avail: '18F',
    cost: 14000
}, {
    _id: 'panther_xxl',
    name: 'Panther XXL',
    type: 'firearms',
    group: 'Cannons & Launchers',
    wireless: false,
    accuracy: 5(7),
    reach: 0,
    damage: '17',
    damageType: 'P',
    armorPiercing: -6,
    mode: 'SS',
    recoil: 0,
    ammo: '15(c)',
    avail: '20F',
    cost: 43000
}]}, (err, body) => {
    if (err) {
        console.log(err);
        return 1;
    }
    return 0;
});