const couchModel = require('../models/couchConnectionModel');
const couchConn  = new couchModel('localhost', '5984');
const couchAdapter = require('../lib/couchAdapter');
const couchdb = new couchAdapter(couchConn);

const skillCollection = couchdb.createDatabase('gear');
skillCollection.bulk({docs: [{
    _id: 'combat_axe',
    name: 'Combat Axe',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 4,
    reach: 2,
    damage: 'STR + 5',
    damageType: 'P',
    armorPiercing: -4,
    avail: '12R',
    cost: 4000
}, {
    _id: 'combat_knife',
    name: 'Combat Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -3,
    avail: '4',
    cost: 300
}, {
    _id: 'forearm_snap_blades',
    name: 'Forearm Snap-Blades',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: true,
    accuracy: 4,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -2,
    avail: '7R',
    cost: 200
}, {
    _id: 'katana',
    name: 'Katana',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 7,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -3,
    avail: '9R',
    cost: 1000
}, {
    _id: 'knife',
    name: 'Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: -1,
    avail: null,
    cost: 10
}, {
    _id: 'pole_arm',
    name: 'Pole Arm',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 5,
    reach: 3,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -2,
    avail: '6R',
    cost: 1000
}, {
    _id: 'survival_knife',
    name: 'Survival Knife',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: -1,
    avail: null,
    cost: 100
}, {
    _id: 'sword',
    name: 'Sword',
    type: 'melee_weapon',
    group: 'Blades',
    wireless: false,
    accuracy: 6,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: -2,
    avail: '5R',
    cost: 500
}, {
    _id: 'club',
    name: 'Club',
    type: 'melee_weapon',
    group: 'Clubs',
    wireless: false,
    accuracy: 4,
    reach: 1,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: 0,
    avail: null,
    cost: 30
}, {
    _id: 'extendable_baton',
    name: 'Extendable Baton',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 5,
    reach: 1,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '4',
    cost: 100
}, {
    _id: 'sap',
    name: 'Sap',
    type: 'melee_weapon',
    group: 'Club',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '2',
    cost: 30
}, {
    _id: 'staff',
    name: 'Staff',
    type: 'melee_weapon',
    group: 'Club',
    wireless: false,
    accuracy: 6,
    reach: 2,
    damage: 'STR + 3',
    damageType: 'P',
    armorPiercing: 0,
    avail: '3',
    cost: 100
}, {
    _id: 'stun_baton',
    name: 'Stun Baton',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 4,
    reach: 1,
    damage: '9',
    damageType: 'S(e)',
    armorPiercing: 0,
    avail: '4',
    cost: 100
}, {
    _id: 'telescoping_staff',
    name: 'Telescoping Staff',
    type: 'melee_weapon',
    group: 'Club',
    wireless: true,
    accuracy: 4,
    reach: 2,
    damage: 'STR + 2',
    damageType: 'P',
    armorPiercing: 0,
    avail: '4',
    cost: 350
}, {
    _id: 'knucks',
    name: 'Knucks',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: false,
    accuracy: -1,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: 0,
    avail: '2R',
    cost: 100
}, {
    _id: 'monofilament_whip',
    name: 'Monofilament Whip',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: true,
    accuracy: 5(7),
    reach: 2,
    damage: '12',
    damageType: 'P',
    armorPiercing: -8,
    avail: '12F',
    cost: 10000
}, {
    _id: 'shock_gloves',
    name: 'Shock Gloves',
    type: 'melee_weapon',
    group: 'Exotic',
    wireless: true,
    accuracy: -1,
    reach: 0,
    damage: '8',
    damageType: 'S(e)',
    armorPiercing: -5,
    avail: '6R',
    cost: 550
}, {
    _id: 'bows',
    name: 'Bows',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: 'Rating + 2',
    damageType: 'P',
    armorPiercing: -1/4,
    avail: '1',
    cost: 100
}, {
    _id: 'light_crossbow',
    name: 'Light Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '5',
    damageType: 'P',
    armorPiercing: -1,
    avail: '2',
    cost: 300
}, {
    _id: 'medium_crossbow',
    name: 'Medium Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: -2,
    avail: '4R',
    cost: 500
}, {
    _id: 'heavy_crossbow',
    name: 'Heavy Crossbow',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 5,
    reach: 0,
    damage: '10',
    damageType: 'P',
    armorPiercing: -2,
    avail: '8R',
    cost: 1000
}, {
    _id: 'bolt',
    name: 'Bolt',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 0,
    reach: 0,
    damage: null,
    damageType: null,
    armorPiercing: 0,
    avail: '2',
    cost: 5
}, {
    _id: 'injection_bolt',
    name: 'Injection Bolt',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: false,
    accuracy: 0,
    reach: 0,
    damage: null,
    damageType: null,
    armorPiercing: 0,
    avail: '8R',
    cost: 50
}, {
    _id: 'throwing_knife_shuriken',
    name: 'Throwing Knife/Shuriken',
    type: 'projectile_throwing_weapon',
    group: 'Projectile/Throwing',
    wireless: true,
    accuracy: 0,
    reach: 0,
    damage: 'STR + 1',
    damageType: 'P',
    armorPiercing: -1,
    avail: '4R',
    cost: 25
}, {
    _id: 'defiance_ex_shocker',
    name: 'Defiance EX Shocker',
    type: 'firearms',
    group: 'Tasers',
    wireless: true,
    accuracy: 4,
    reach: 0,
    damage: '9',
    damageType: 'S(e)',
    armorPiercing: -5,
    mode: 'SS',
    recoil: null,
    ammo: '4(m)',
    avail: null,
    cost: 250
}, {
    _id: 'yamaha_pulsar',
    name: 'Yamaha Pulsar',
    type: 'firearms',
    group: 'Tasers',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: '7',
    damageType: 'S(e)',
    armorPiercing: -5,
    mode: 'SA',
    recoil: null,
    ammo: '4(m)',
    avail: null,
    cost: 180
}, {
    _id: 'fichetti_tiffani_needler',
    name: 'Fichetti Tiffani Needler',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: true,
    accuracy: 5,
    reach: 0,
    damage: '8',
    damageType: 'P(f)',
    armorPiercing: +5,
    mode: 'SA',
    recoil: null,
    ammo: '4(c)',
    avail: '5R',
    cost: 1000
}, {
    _id: 'streetline_special',
    name: 'Streetline Special',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '6(c)',
    avail: '4R',
    cost: 120
}, {
    _id: 'walther_palm_pistol',
    name: 'Walther Palm Pistol',
    type: 'firearms',
    group: 'Hold-Outs',
    wireless: false,
    accuracy: 4,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SS/BF',
    recoil: null,
    ammo: '2(b)',
    avail: '4R',
    cost: 180
}, {
    _id: 'ares_light_fire_75',
    name: 'Ares Light Fire 75',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6(8),
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '16(c)',
    avail: '6F',
    cost: 1250
}, {
    _id: 'ares_light_fire_70',
    name: 'Ares Light Fire 70',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '16(c)',
    avail: '3R',
    cost: 200
}, {
    _id: 'beretta_201T',
    name: 'Beretta 201T',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6,
    reach: 0,
    damage: '6',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA/BF',
    recoil: 1,
    ammo: '21(c)',
    avail: '7R',
    cost: 210
}, {
    _id: 'colt_america_L36',
    name: 'Colt America L36',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 7,
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: null,
    ammo: '11(c)',
    avail: '4R',
    cost: 320
}, {
    _id: 'fichetti_security_600',
    name: 'Fichetti Security 600',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 6(7),
    reach: 0,
    damage: '7',
    damageType: 'P',
    armorPiercing: 0,
    mode: 'SA',
    recoil: 1,
    ammo: '30(c)',
    avail: '6R',
    cost: 350
}, {
    _id: 'taurus_omni_6',
    name: 'Taurus Omni-6',
    type: 'firearms',
    group: 'Light Pistols',
    wireless: false,
    accuracy: 5(6),
    reach: 0,
    damage: '6/7',
    damageType: 'P',
    armorPiercing: -1,
    mode: 'SA/SS',
    recoil: null,
    ammo: '6(cy)',
    avail: '3R',
    cost: 300
}]}, (err, body) => {
    if (err) {
        console.log(err);
        return 1;
    }
    return 0;
});